name: generate animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar manualmente
  workflow_dispatch:

  # Executa sempre que houver push na branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write  # Permite escrever na branch de output
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Gera a animação em SVG
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: PPedrosouza
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica os SVGs na branch output
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
